from enum import Enum


class EngineState(Enum):

    STARTING = "STARTING"

    SYNCHRONIZING = "SYNCHRONIZING"

    READY = "READY"

    WAITING_FOR_CANDLE = "WAITING_FOR_CANDLE"

    GENERATING_SIGNAL = "GENERATING_SIGNAL"

    PLACING_ORDER = "PLACING_ORDER"

    WAITING_FOR_FILL = "WAITING_FOR_FILL"

    IN_POSITION = "IN_POSITION"

    EXITING_POSITION = "EXITING_POSITION"

    ERROR = "ERROR"

    STOPPED = "STOPPED"