from enum import Enum


class MarketRegime(Enum):

    TRENDING = "TRENDING"
    RANGING = "RANGING"

    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"

    HIGH_LIQUIDITY = "HIGH_LIQUIDITY"
    LOW_LIQUIDITY = "LOW_LIQUIDITY"

    UNKNOWN = "UNKNOWN"