class EventNames:

    ORDER_SUBMITTED = "ORDER_SUBMITTED"

    ORDER_FILLED = "ORDER_FILLED"

    POSITION_OPENED = "POSITION_OPENED"

    POSITION_CLOSED = "POSITION_CLOSED"

    STOP_MOVED = "STOP_MOVED"

    TAKE_PROFIT_HIT = "TAKE_PROFIT_HIT"

    STOP_LOSS_HIT = "STOP_LOSS_HIT"

    BREAK_EVEN_ACTIVATED = "BREAK_EVEN_ACTIVATED"

    TRAILING_STOP_ACTIVATED = "TRAILING_STOP_ACTIVATED"

    TRAILING_STOP_MOVED = "TRAILING_STOP_MOVED"